
CREATE DATABASE IF EXISTS employeeDB;

-- Use the database
USE employeeDB;
create database IF NOT EXISTS hospitalDB;
use hospitalDB;


CREATE TABLE IF NOT EXISTS patients (
    PatientID INT PRIMARY KEY,
    P_Name VARCHAR(50),
    Gender VARCHAR(10),
    Age INT,
    BloodGroup VARCHAR(5),
    Disease VARCHAR(50),
    WardNo INT,
    AdmissionDate DATE,
    DischargeDate DATE,
    DoctorAssigned VARCHAR(50)
);
CREATE TABLE IF NOT EXISTS appointments (
    AppointmentID INT PRIMARY KEY,
    PatientID INT,
    AppointmentDate DATE,
    Status VARCHAR(20),  -- e.g., Completed, Pending, Cancelled
    FOREIGN KEY (PatientID) REFERENCES patients(PatientID)
);
INSERT INTO patients(PatientID,P_Name,Gender,Age,BloodGroup,Disease,WardNo,AdmissionDate,DischargeDate,DoctorAssigned) VALUES
(101, 'John Doe', 'Male', 45, 'A+', 'Diabetes', 12, '2023-01-10', '2023-01-20', 'Dr. Smith'),
(102, 'Jane Smith', 'Female', 30, 'B+', 'Hypertension', 15, '2023-02-05', NULL, 'Dr. Lee'),
(103, 'Alice Brown', 'Female', 25, 'O-', 'Flu', 10, '2023-03-01', '2023-03-05', 'Dr. Smith'),
(104, 'Bob White', 'Male', 60, 'AB+', 'Heart Disease', 20, '2023-01-15', '2023-01-25', 'Dr. Lee'),
(105, 'Charlie Green', 'Male', 35, 'A+', 'Diabetes', 12, '2023-02-10', NULL, 'Dr. Smith');

INSERT INTO appointments VALUES
(1, 101, '2023-01-12', 'Completed'),
(2, 102, '2023-02-07', 'Pending'),
(3, 103, '2023-03-02', 'Completed'),
(4, 104, '2023-01-18', 'Completed'),
(5, 105, '2023-02-15', 'Pending');


SELECT * FROM PATIENTS;
SELECT * FROM APPOINTMENTS;
SELECT APPOINTMENT,STATUS FROM APPOINTMENTS;

/* SELECT & DISTINCT


List all unique diseases in the hospital:*/
SELECT DISTINCT BLOODGROUP FROM PATIENTS;


/*List unique blood groups of patients:*/




/*AS (Alias)

Show patient names and their ages with aliases:*/
SELECT P_NAME AS PATIENTNAME,AGE AS PATIENTAGE FROM PATIENTS;

/*Show disease and assigned doctor with readable column names:*/
SELECT DISEASE AS PATIENT_DISEASE,DOCTORASSIGNED AS ASSIGNED_DOCTOR FROM PATIENTS;

/*WHERE Clause & Comparison Operators

Find patients older than 40:*/
SELECT * FROM PATIENTS WHERE AGE>40;

/*Find patients with Diabetes:*/
SELECT * FROM PATIENTS WHERE DISEASE='DIABETES';

/*Find patients not discharged yet:*/
SELECT * FROM PATIENTS WHERE DISCHARGEDATE IS NULL;
SELECT * FROM PATIENTS WHERE DISCHARGEDATE IS NOT NULL;

/*Logical Operators (AND, OR, NOT)

Patients older than 30 AND have Diabetes:*/
SELECT * FROM PATIENTS WHERE AGE>30 AND DISEASE='DIABETES';
SELECT * FROM PATIENTS WHERE AGE>30 AND DISEASE='HEART DISEASE';
/*Patients in WardNo 12 OR WardNo 15:*/
SELECT * FROM PATIENTS WHERE WARDNO=12 OR WARDNO=15;

/*Patients NOT assigned to Dr. Lee:*/
SELECT * FROM PATIENTS WHERE NOT DOCTORASSIGNED="DR. LEE";

/*IN, NOT IN

Patients assigned to either Dr. Smith or Dr. Lee:*/
SELECT * FROM PATIENTS WHERE DOCTORASSIGNED IN("DR. LEE","DR. SMITH");

SELECT * FROM PATIENTS WHERE BLOODGROUP IN("A+","B+");
/*Patients not assigned to Dr. Smith:*/
SELECT * FROM PATIENTS WHERE NOT DOCTORASSIGNMENT="DR.SMITH";


/*BETWEEN, NOT BETWEEN

Patients aged between 30 and 50:*/
SELECT * FROM PATIENTS WHERE AGE BETWEEN 30 AND 50;

SELECT P_NAME FROM PATIENTS WHERE P_NAME NOT LIKE "J%";
/*Patients not aged between 25 and 40:*/
SELECT * FROM PATIENTS WHERE AGE NOT BETWEEN 25 AND 40;
SELECT * FROM appointments WHERE status = 'Pending' OR patient_id = 105;
/*IS NULL / IS NOT NULL

Patients still admitted (DischargeDate NULL):*/



/*Patients already discharged (DischargeDate NOT NULL):*/
CREATE DATABASE IF NOT exists hospitaldb;
use hospitaldb;


/*ORDER BY (Sorting Results)
The ORDER BY clause is used to sort results in ascending (ASC) or descending (DESC) order.
🧩 Examples: - Sort patients by age (ascending)*/



/*2️.Sort patients by age (descending)*/


/* 3.Sort by multiple columns (by Doctor, then Age descending)*/



/*LIMIT – Restricting Records

a. Display the top 3 highest billed patients:*/



/*b. Show 2 most recent completed appointments:*/

SELECT * 
FROM appointments 
WHERE Status = 'Completed' 
ORDER BY AppointmentDate DESC 
LIMIT 2;

/*Aggregate Functions – Data Summaries
Count of total patients admitted:*/
SELECT COUNT(*) AS TOTAL_APPOINMENTS
FROM APPOINTMENTS;

/*Average bill amount for discharged patients:*/
SELECT AVG(BILLAMOUNT) FROM PATIENTS
WHERE DISCHARGE IS NOT NULL;


SELECT AVG(BillAmount) AS AvgBill_Discharge
FROM Patients
WHERE DischargeDate IS NOT NULL;


/* imputing null values using Average for null values*/
SELECT * FROM PATIENTS;
SELECT AVG(AGE) FROM PATIENTS;
SET SQL_SAFE_UPDATE=0;
UPDATE PATIENTS 
SET AGE=41
WHERE AGE IS NULL;

/*Total revenue generated by Dr. Smith:*/
SELECT SUM9BILLAMOUNT) FROM PATIENTS
WHERE DOCTORASSIGNED"DR. SMITH";

/*. Find the oldest and youngest patient in the hospital:*/
SELECT MAX(AGE) AS OLDEST_PATIENTS, MIN(AGE) AS YOUNGEST-PATIENTS FROM PAATIENTS;


/*Impute most common WardNo for patients missing WardNo*/

select wardno from patients
group by waedno
order by count(*) desc
limit 1;



/*GROUP BY – Grouping and Summarizing Data

a. Count patients assigned to each doctor:*/
SELECT DOCTORASSIGNMENT,COUNT(*) AS PATIENTSCOUNT
FROM PATIENTS 
GROUP BY DOCTORASSIGNED

/*b. Calculate the average bill amount for each disease:*/
SELECT DISEASE.AVG(BILLAMOUNT) AS AVG_BILLAMOUNT FROM PATIENTS
GROUP BY DISEASE;


/*c. Count number of appointments by status (Completed, Pending, Cancelled):*/
SELECT STATUS,COUNT(*)  as total_appoinments
from appoinments
group by statuus;

/*d. Calculate total revenue per ward:*/



/*HAVING – Filtering Aggregated Results

a. Doctors treating more than 1 patient:*/
select doctorassigned,count(*) as totalpatient
from patients
group by doctorassigned
having count(*)>1;



/*b. Diseases with average bill amount greater than ₹20,000:*/
select disease,avg(billaMOUNT) AS AVG_BILLAMOUNT
FROM PATIENTS 
GROUP BY DISEASE 
HAVING AVG(BILLAMOUNT)>20000;


/*c. Wards with total revenue more than ₹30,000:*/
SELECT WardNo, SUM(BillAmount) AS TotalRevenue
FROM patients
GROUP BY WardNo
HAVING SUM(BillAmount) > 30000;







/* Advance concept 

Combining Clauses

/*Appointments that are Pending or belong to patientID 105:*/


/* Find female patients aged 25-35, assigned to Dr. Smith:*/

SELECT P_Name, Age, Gender, DoctorAssigned 
FROM patients 
WHERE Gender = 'Female' 
  AND Age BETWEEN 25 AND 35 
  AND DoctorAssigned = 'Dr. Smith';


SELECT * FROM PATIENTS WHERE DEPTID=1 OR DEPT=3

-- Create Departments table
CREATE TABLE Departments (
    department_id INT PRIMARY KEY,
    department_name VARCHAR(100) NOT NULL UNIQUE
);

-- Create Location table
CREATE TABLE Location (
    location_id INT AUTO_INCREMENT PRIMARY KEY,
    location_name VARCHAR(100) NOT NULL UNIQUE
);

-- Create Employees table
CREATE TABLE Employees (
    emp_id INT PRIMARY KEY,
    emp_name VARCHAR(100) NOT NULL,
    gender CHAR(1) CHECK (gender IN ('M', 'F')),
    age INT CHECK (age >= 18),
    designation VARCHAR(100),
    hire_date DATE DEFAULT (CURRENT_DATE),
    department_id INT,
    location_id INT,
    FOREIGN KEY (department_id) REFERENCES Departments(department_id),
    FOREIGN KEY (location_id) REFERENCES Location(location_id)
);

-- Add new column "email" to Employees table
ALTER TABLE Employees ADD COLUMN email VARCHAR(150);

-- Modify data type of "designation"
ALTER TABLE Employees MODIFY designation VARCHAR(255);

-- Drop the "age" column
ALTER TABLE Employees DROP COLUMN age;

-- Rename "hire_date" to "date_of_joining"
ALTER TABLE Employees CHANGE hire_date date_of_joining DATE;

-- Rename tables
RENAME TABLE Departments TO Departments_Info;
RENAME TABLE Location TO Locations;

-- Truncate Employees table
TRUNCATE TABLE Employees;

-- Drop Employees table
DROP TABLE Employees;

-- Drop the database
DROP DATABASE employee;

       